module.exports = {
  collection: [
    {
      id: 1,
      name: "Bulbasaur",
      typeOne: "Grass",
      typeTwo: "Poison",
      total: 318,
      hp: 45,
      attack: 49,
      defense: 49,
      specialAttack: 65,
      specialDefense: 65,
      speed: 45,
      generation: 1,
      isLegendary: false
    },
    {
      id: 4,
      name: "Charmander",
      typeOne: "Fire",
      typeTwo: "",
      total: 309,
      hp: 39,
      attack: 52,
      defense: 43,
      specialAttack: 60,
      specialDefense: 50,
      speed: 65,
      generation: 1,
      isLegendary: false
    },
    {
      id: 25,
      name: "Pikachu",
      typeOne: "Electric",
      typeTwo: "",
      total: 320,
      hp: 35,
      attack: 55,
      defense: 40,
      specialAttack: 50,
      specialDefense: 50,
      speed: 90,
      generation: 1,
      isLegendary: false
    },
    {
      id: 5,
      name: "Charmeleon",
      typeOne: "Fire",
      typeTwo: "",
      total: 405,
      hp: 58,
      attack: 64,
      defense: 58,
      specialAttack: 80,
      specialDefense: 65,
      speed: 80,
      generation: 1,
      isLegendary: false
    },
    {
      id: 10,
      name: "Caterpie",
      typeOne: "Bug",
      typeTwo: "",
      total: 195,
      hp: 45,
      attack: 30,
      defense: 35,
      specialAttack: 20,
      specialDefense: 20,
      speed: 45,
      generation: 1,
      isLegendary: false
    },
    {
      id: 7,
      name: "Squirtle",
      typeOne: "Water",
      typeTwo: "",
      total: 314,
      hp: 44,
      attack: 48,
      defense: 65,
      specialAttack: 50,
      specialDefense: 64,
      speed: 43,
      generation: 1,
      isLegendary: false
    }
  ],
  pokedex: [
    {
      id: 1,
      name: "Bulbasaur",
      typeOne: "Grass",
      typeTwo: "Poison",
      total: 318,
      hp: 45,
      attack: 49,
      defense: 49,
      specialAttack: 65,
      specialDefense: 65,
      speed: 45,
      generation: 1,
      isLegendary: false
    },
    {
      id: 2,
      name: "Ivysaur",
      typeOne: "Grass",
      typeTwo: "Poison",
      total: 405,
      hp: 60,
      attack: 62,
      defense: 63,
      specialAttack: 80,
      specialDefense: 80,
      speed: 60,
      generation: 1,
      isLegendary: false
    },
    {
      id: 3,
      name: "Venusaur",
      typeOne: "Grass",
      typeTwo: "Poison",
      total: 525,
      hp: 80,
      attack: 82,
      defense: 83,
      specialAttack: 100,
      specialDefense: 100,
      speed: 80,
      generation: 1,
      isLegendary: false
    },
    {
      id: 4,
      name: "Charmander",
      typeOne: "Fire",
      typeTwo: "",
      total: 309,
      hp: 39,
      attack: 52,
      defense: 43,
      specialAttack: 60,
      specialDefense: 50,
      speed: 65,
      generation: 1,
      isLegendary: false
    },
    {
      id: 5,
      name: "Charmeleon",
      typeOne: "Fire",
      typeTwo: "",
      total: 405,
      hp: 58,
      attack: 64,
      defense: 58,
      specialAttack: 80,
      specialDefense: 65,
      speed: 80,
      generation: 1,
      isLegendary: false
    },
    {
      id: 6,
      name: "Charizard",
      typeOne: "Fire",
      typeTwo: "Flying",
      total: 534,
      hp: 78,
      attack: 84,
      defense: 78,
      specialAttack: 109,
      specialDefense: 85,
      speed: 100,
      generation: 1,
      isLegendary: false
    },
    {
      id: 7,
      name: "Squirtle",
      typeOne: "Water",
      typeTwo: "",
      total: 314,
      hp: 44,
      attack: 48,
      defense: 65,
      specialAttack: 50,
      specialDefense: 64,
      speed: 43,
      generation: 1,
      isLegendary: false
    },
    {
      id: 8,
      name: "Wartortle",
      typeOne: "Water",
      typeTwo: "",
      total: 405,
      hp: 59,
      attack: 63,
      defense: 80,
      specialAttack: 65,
      specialDefense: 80,
      speed: 58,
      generation: 1,
      isLegendary: false
    },
    {
      id: 9,
      name: "Blastoise",
      typeOne: "Water",
      typeTwo: "",
      total: 530,
      hp: 79,
      attack: 83,
      defense: 100,
      specialAttack: 85,
      specialDefense: 105,
      speed: 78,
      generation: 1,
      isLegendary: false
    },
    {
      id: 10,
      name: "Caterpie",
      typeOne: "Bug",
      typeTwo: "",
      total: 195,
      hp: 45,
      attack: 30,
      defense: 35,
      specialAttack: 20,
      specialDefense: 20,
      speed: 45,
      generation: 1,
      isLegendary: false
    },
    {
      id: 11,
      name: "Metapod",
      typeOne: "Bug",
      typeTwo: "",
      total: 205,
      hp: 50,
      attack: 20,
      defense: 55,
      specialAttack: 25,
      specialDefense: 25,
      speed: 30,
      generation: 1,
      isLegendary: false
    },
    {
      id: 12,
      name: "Butterfree",
      typeOne: "Bug",
      typeTwo: "Flying",
      total: 395,
      hp: 60,
      attack: 45,
      defense: 50,
      specialAttack: 90,
      specialDefense: 80,
      speed: 70,
      generation: 1,
      isLegendary: false
    },
    {
      id: 13,
      name: "Weedle",
      typeOne: "Bug",
      typeTwo: "Poison",
      total: 195,
      hp: 40,
      attack: 35,
      defense: 30,
      specialAttack: 20,
      specialDefense: 20,
      speed: 50,
      generation: 1,
      isLegendary: false
    },
    {
      id: 14,
      name: "Kakuna",
      typeOne: "Bug",
      typeTwo: "Poison",
      total: 205,
      hp: 45,
      attack: 25,
      defense: 50,
      specialAttack: 25,
      specialDefense: 25,
      speed: 35,
      generation: 1,
      isLegendary: false
    },
    {
      id: 15,
      name: "Beedrill",
      typeOne: "Bug",
      typeTwo: "Poison",
      total: 395,
      hp: 65,
      attack: 90,
      defense: 40,
      specialAttack: 45,
      specialDefense: 80,
      speed: 75,
      generation: 1,
      isLegendary: false
    },
    {
      id: 16,
      name: "Pidgey",
      typeOne: "Normal",
      typeTwo: "Flying",
      total: 251,
      hp: 40,
      attack: 45,
      defense: 40,
      specialAttack: 35,
      specialDefense: 35,
      speed: 56,
      generation: 1,
      isLegendary: false
    },
    {
      id: 17,
      name: "Pidgeotto",
      typeOne: "Normal",
      typeTwo: "Flying",
      total: 349,
      hp: 63,
      attack: 60,
      defense: 55,
      specialAttack: 50,
      specialDefense: 50,
      speed: 71,
      generation: 1,
      isLegendary: false
    },
    {
      id: 18,
      name: "Pidgeot",
      typeOne: "Normal",
      typeTwo: "Flying",
      total: 479,
      hp: 83,
      attack: 80,
      defense: 75,
      specialAttack: 70,
      specialDefense: 70,
      speed: 101,
      generation: 1,
      isLegendary: false
    },
    {
      id: 19,
      name: "Rattata",
      typeOne: "Normal",
      typeTwo: "",
      total: 253,
      hp: 30,
      attack: 56,
      defense: 35,
      specialAttack: 25,
      specialDefense: 35,
      speed: 72,
      generation: 1,
      isLegendary: false
    },
    {
      id: 20,
      name: "Raticate",
      typeOne: "Normal",
      typeTwo: "",
      total: 413,
      hp: 55,
      attack: 81,
      defense: 60,
      specialAttack: 50,
      specialDefense: 70,
      speed: 97,
      generation: 1,
      isLegendary: false
    },
    {
      id: 21,
      name: "Spearow",
      typeOne: "Normal",
      typeTwo: "Flying",
      total: 262,
      hp: 40,
      attack: 60,
      defense: 30,
      specialAttack: 31,
      specialDefense: 31,
      speed: 70,
      generation: 1,
      isLegendary: false
    },
    {
      id: 22,
      name: "Fearow",
      typeOne: "Normal",
      typeTwo: "Flying",
      total: 442,
      hp: 65,
      attack: 90,
      defense: 65,
      specialAttack: 61,
      specialDefense: 61,
      speed: 100,
      generation: 1,
      isLegendary: false
    },
    {
      id: 23,
      name: "Ekans",
      typeOne: "Poison",
      typeTwo: "",
      total: 288,
      hp: 35,
      attack: 60,
      defense: 44,
      specialAttack: 40,
      specialDefense: 54,
      speed: 55,
      generation: 1,
      isLegendary: false
    },
    {
      id: 24,
      name: "Arbok",
      typeOne: "Poison",
      typeTwo: "",
      total: 438,
      hp: 60,
      attack: 85,
      defense: 69,
      specialAttack: 65,
      specialDefense: 79,
      speed: 80,
      generation: 1,
      isLegendary: false
    },
    {
      id: 25,
      name: "Pikachu",
      typeOne: "Electric",
      typeTwo: "",
      total: 320,
      hp: 35,
      attack: 55,
      defense: 40,
      specialAttack: 50,
      specialDefense: 50,
      speed: 90,
      generation: 1,
      isLegendary: false
    },
    {
      id: 26,
      name: "Raichu",
      typeOne: "Electric",
      typeTwo: "",
      total: 485,
      hp: 60,
      attack: 90,
      defense: 55,
      specialAttack: 90,
      specialDefense: 80,
      speed: 110,
      generation: 1,
      isLegendary: false
    },
    {
      id: 27,
      name: "Sandshrew",
      typeOne: "Ground",
      typeTwo: "",
      total: 300,
      hp: 50,
      attack: 75,
      defense: 85,
      specialAttack: 20,
      specialDefense: 30,
      speed: 40,
      generation: 1,
      isLegendary: false
    },
    {
      id: 28,
      name: "Sandslash",
      typeOne: "Ground",
      typeTwo: "",
      total: 450,
      hp: 75,
      attack: 100,
      defense: 110,
      specialAttack: 45,
      specialDefense: 55,
      speed: 65,
      generation: 1,
      isLegendary: false
    },
    {
      id: 29,
      name: "Nidoran♀",
      typeOne: "Poison",
      typeTwo: "",
      total: 275,
      hp: 55,
      attack: 47,
      defense: 52,
      specialAttack: 40,
      specialDefense: 40,
      speed: 41,
      generation: 1,
      isLegendary: false
    },
    {
      id: 30,
      name: "Nidorina",
      typeOne: "Poison",
      typeTwo: "",
      total: 365,
      hp: 70,
      attack: 62,
      defense: 67,
      specialAttack: 55,
      specialDefense: 55,
      speed: 56,
      generation: 1,
      isLegendary: false
    },
    {
      id: 31,
      name: "Nidoqueen",
      typeOne: "Poison",
      typeTwo: "Ground",
      total: 505,
      hp: 90,
      attack: 92,
      defense: 87,
      specialAttack: 75,
      specialDefense: 85,
      speed: 76,
      generation: 1,
      isLegendary: false
    },
    {
      id: 32,
      name: "Nidoran♂",
      typeOne: "Poison",
      typeTwo: "",
      total: 273,
      hp: 46,
      attack: 57,
      defense: 40,
      specialAttack: 40,
      specialDefense: 40,
      speed: 50,
      generation: 1,
      isLegendary: false
    },
    {
      id: 33,
      name: "Nidorino",
      typeOne: "Poison",
      typeTwo: "",
      total: 365,
      hp: 61,
      attack: 72,
      defense: 57,
      specialAttack: 55,
      specialDefense: 55,
      speed: 65,
      generation: 1,
      isLegendary: false
    },
    {
      id: 34,
      name: "Nidoking",
      typeOne: "Poison",
      typeTwo: "Ground",
      total: 505,
      hp: 81,
      attack: 102,
      defense: 77,
      specialAttack: 85,
      specialDefense: 75,
      speed: 85,
      generation: 1,
      isLegendary: false
    },
    {
      id: 35,
      name: "Clefairy",
      typeOne: "Fairy",
      typeTwo: "",
      total: 323,
      hp: 70,
      attack: 45,
      defense: 48,
      specialAttack: 60,
      specialDefense: 65,
      speed: 35,
      generation: 1,
      isLegendary: false
    },
    {
      id: 36,
      name: "Clefable",
      typeOne: "Fairy",
      typeTwo: "",
      total: 483,
      hp: 95,
      attack: 70,
      defense: 73,
      specialAttack: 95,
      specialDefense: 90,
      speed: 60,
      generation: 1,
      isLegendary: false
    },
    {
      id: 37,
      name: "Vulpix",
      typeOne: "Fire",
      typeTwo: "",
      total: 299,
      hp: 38,
      attack: 41,
      defense: 40,
      specialAttack: 50,
      specialDefense: 65,
      speed: 65,
      generation: 1,
      isLegendary: false
    },
    {
      id: 38,
      name: "Ninetales",
      typeOne: "Fire",
      typeTwo: "",
      total: 505,
      hp: 73,
      attack: 76,
      defense: 75,
      specialAttack: 81,
      specialDefense: 100,
      speed: 100,
      generation: 1,
      isLegendary: false
    },
    {
      id: 39,
      name: "Jigglypuff",
      typeOne: "Normal",
      typeTwo: "Fairy",
      total: 270,
      hp: 115,
      attack: 45,
      defense: 20,
      specialAttack: 45,
      specialDefense: 25,
      speed: 20,
      generation: 1,
      isLegendary: false
    },
    {
      id: 40,
      name: "Wigglytuff",
      typeOne: "Normal",
      typeTwo: "Fairy",
      total: 435,
      hp: 140,
      attack: 70,
      defense: 45,
      specialAttack: 85,
      specialDefense: 50,
      speed: 45,
      generation: 1,
      isLegendary: false
    },
    {
      id: 41,
      name: "Zubat",
      typeOne: "Poison",
      typeTwo: "Flying",
      total: 245,
      hp: 40,
      attack: 45,
      defense: 35,
      specialAttack: 30,
      specialDefense: 40,
      speed: 55,
      generation: 1,
      isLegendary: false
    },
    {
      id: 42,
      name: "Golbat",
      typeOne: "Poison",
      typeTwo: "Flying",
      total: 455,
      hp: 75,
      attack: 80,
      defense: 70,
      specialAttack: 65,
      specialDefense: 75,
      speed: 90,
      generation: 1,
      isLegendary: false
    },
    {
      id: 43,
      name: "Oddish",
      typeOne: "Grass",
      typeTwo: "Poison",
      total: 320,
      hp: 45,
      attack: 50,
      defense: 55,
      specialAttack: 75,
      specialDefense: 65,
      speed: 30,
      generation: 1,
      isLegendary: false
    },
    {
      id: 44,
      name: "Gloom",
      typeOne: "Grass",
      typeTwo: "Poison",
      total: 395,
      hp: 60,
      attack: 65,
      defense: 70,
      specialAttack: 85,
      specialDefense: 75,
      speed: 40,
      generation: 1,
      isLegendary: false
    },
    {
      id: 45,
      name: "Vileplume",
      typeOne: "Grass",
      typeTwo: "Poison",
      total: 490,
      hp: 75,
      attack: 80,
      defense: 85,
      specialAttack: 110,
      specialDefense: 90,
      speed: 50,
      generation: 1,
      isLegendary: false
    },
    {
      id: 46,
      name: "Paras",
      typeOne: "Bug",
      typeTwo: "Grass",
      total: 285,
      hp: 35,
      attack: 70,
      defense: 55,
      specialAttack: 45,
      specialDefense: 55,
      speed: 25,
      generation: 1,
      isLegendary: false
    },
    {
      id: 47,
      name: "Parasect",
      typeOne: "Bug",
      typeTwo: "Grass",
      total: 405,
      hp: 60,
      attack: 95,
      defense: 80,
      specialAttack: 60,
      specialDefense: 80,
      speed: 30,
      generation: 1,
      isLegendary: false
    },
    {
      id: 48,
      name: "Venonat",
      typeOne: "Bug",
      typeTwo: "Poison",
      total: 305,
      hp: 60,
      attack: 55,
      defense: 50,
      specialAttack: 40,
      specialDefense: 55,
      speed: 45,
      generation: 1,
      isLegendary: false
    },
    {
      id: 49,
      name: "Venomoth",
      typeOne: "Bug",
      typeTwo: "Poison",
      total: 450,
      hp: 70,
      attack: 65,
      defense: 60,
      specialAttack: 90,
      specialDefense: 75,
      speed: 90,
      generation: 1,
      isLegendary: false
    },
    {
      id: 50,
      name: "Diglett",
      typeOne: "Ground",
      typeTwo: "",
      total: 265,
      hp: 10,
      attack: 55,
      defense: 25,
      specialAttack: 35,
      specialDefense: 45,
      speed: 95,
      generation: 1,
      isLegendary: false
    },
    {
      id: 51,
      name: "Dugtrio",
      typeOne: "Ground",
      typeTwo: "",
      total: 405,
      hp: 35,
      attack: 80,
      defense: 50,
      specialAttack: 50,
      specialDefense: 70,
      speed: 120,
      generation: 1,
      isLegendary: false
    },
    {
      id: 52,
      name: "Meowth",
      typeOne: "Normal",
      typeTwo: "",
      total: 290,
      hp: 40,
      attack: 45,
      defense: 35,
      specialAttack: 40,
      specialDefense: 40,
      speed: 90,
      generation: 1,
      isLegendary: false
    },
    {
      id: 53,
      name: "Persian",
      typeOne: "Normal",
      typeTwo: "",
      total: 440,
      hp: 65,
      attack: 70,
      defense: 60,
      specialAttack: 65,
      specialDefense: 65,
      speed: 115,
      generation: 1,
      isLegendary: false
    },
    {
      id: 54,
      name: "Psyduck",
      typeOne: "Water",
      typeTwo: "",
      total: 320,
      hp: 50,
      attack: 52,
      defense: 48,
      specialAttack: 65,
      specialDefense: 50,
      speed: 55,
      generation: 1,
      isLegendary: false
    },
    {
      id: 55,
      name: "Golduck",
      typeOne: "Water",
      typeTwo: "",
      total: 500,
      hp: 80,
      attack: 82,
      defense: 78,
      specialAttack: 95,
      specialDefense: 80,
      speed: 85,
      generation: 1,
      isLegendary: false
    },
    {
      id: 56,
      name: "Mankey",
      typeOne: "Fighting",
      typeTwo: "",
      total: 305,
      hp: 40,
      attack: 80,
      defense: 35,
      specialAttack: 35,
      specialDefense: 45,
      speed: 70,
      generation: 1,
      isLegendary: false
    },
    {
      id: 57,
      name: "Primeape",
      typeOne: "Fighting",
      typeTwo: "",
      total: 455,
      hp: 65,
      attack: 105,
      defense: 60,
      specialAttack: 60,
      specialDefense: 70,
      speed: 95,
      generation: 1,
      isLegendary: false
    },
    {
      id: 58,
      name: "Growlithe",
      typeOne: "Fire",
      typeTwo: "",
      total: 350,
      hp: 55,
      attack: 70,
      defense: 45,
      specialAttack: 70,
      specialDefense: 50,
      speed: 60,
      generation: 1,
      isLegendary: false
    },
    {
      id: 59,
      name: "Arcanine",
      typeOne: "Fire",
      typeTwo: "",
      total: 555,
      hp: 90,
      attack: 110,
      defense: 80,
      specialAttack: 100,
      specialDefense: 80,
      speed: 95,
      generation: 1,
      isLegendary: false
    },
    {
      id: 60,
      name: "Poliwag",
      typeOne: "Water",
      typeTwo: "",
      total: 300,
      hp: 40,
      attack: 50,
      defense: 40,
      specialAttack: 40,
      specialDefense: 40,
      speed: 90,
      generation: 1,
      isLegendary: false
    },
    {
      id: 61,
      name: "Poliwhirl",
      typeOne: "Water",
      typeTwo: "",
      total: 385,
      hp: 65,
      attack: 65,
      defense: 65,
      specialAttack: 50,
      specialDefense: 50,
      speed: 90,
      generation: 1,
      isLegendary: false
    },
    {
      id: 62,
      name: "Poliwrath",
      typeOne: "Water",
      typeTwo: "Fighting",
      total: 510,
      hp: 90,
      attack: 95,
      defense: 95,
      specialAttack: 70,
      specialDefense: 90,
      speed: 70,
      generation: 1,
      isLegendary: false
    },
    {
      id: 63,
      name: "Abra",
      typeOne: "Psychic",
      typeTwo: "",
      total: 310,
      hp: 25,
      attack: 20,
      defense: 15,
      specialAttack: 105,
      specialDefense: 55,
      speed: 90,
      generation: 1,
      isLegendary: false
    },
    {
      id: 64,
      name: "Kadabra",
      typeOne: "Psychic",
      typeTwo: "",
      total: 400,
      hp: 40,
      attack: 35,
      defense: 30,
      specialAttack: 120,
      specialDefense: 70,
      speed: 105,
      generation: 1,
      isLegendary: false
    },
    {
      id: 65,
      name: "Alakazam",
      typeOne: "Psychic",
      typeTwo: "",
      total: 500,
      hp: 55,
      attack: 50,
      defense: 45,
      specialAttack: 135,
      specialDefense: 95,
      speed: 120,
      generation: 1,
      isLegendary: false
    },
    {
      id: 66,
      name: "Machop",
      typeOne: "Fighting",
      typeTwo: "",
      total: 305,
      hp: 70,
      attack: 80,
      defense: 50,
      specialAttack: 35,
      specialDefense: 35,
      speed: 35,
      generation: 1,
      isLegendary: false
    },
    {
      id: 67,
      name: "Machoke",
      typeOne: "Fighting",
      typeTwo: "",
      total: 405,
      hp: 80,
      attack: 100,
      defense: 70,
      specialAttack: 50,
      specialDefense: 60,
      speed: 45,
      generation: 1,
      isLegendary: false
    },
    {
      id: 68,
      name: "Machamp",
      typeOne: "Fighting",
      typeTwo: "",
      total: 505,
      hp: 90,
      attack: 130,
      defense: 80,
      specialAttack: 65,
      specialDefense: 85,
      speed: 55,
      generation: 1,
      isLegendary: false
    },
    {
      id: 69,
      name: "Bellsprout",
      typeOne: "Grass",
      typeTwo: "Poison",
      total: 300,
      hp: 50,
      attack: 75,
      defense: 35,
      specialAttack: 70,
      specialDefense: 30,
      speed: 40,
      generation: 1,
      isLegendary: false
    },
    {
      id: 70,
      name: "Weepinbell",
      typeOne: "Grass",
      typeTwo: "Poison",
      total: 390,
      hp: 65,
      attack: 90,
      defense: 50,
      specialAttack: 85,
      specialDefense: 45,
      speed: 55,
      generation: 1,
      isLegendary: false
    },
    {
      id: 71,
      name: "Victreebel",
      typeOne: "Grass",
      typeTwo: "Poison",
      total: 490,
      hp: 80,
      attack: 105,
      defense: 65,
      specialAttack: 100,
      specialDefense: 70,
      speed: 70,
      generation: 1,
      isLegendary: false
    },
    {
      id: 72,
      name: "Tentacool",
      typeOne: "Water",
      typeTwo: "Poison",
      total: 335,
      hp: 40,
      attack: 40,
      defense: 35,
      specialAttack: 50,
      specialDefense: 100,
      speed: 70,
      generation: 1,
      isLegendary: false
    },
    {
      id: 73,
      name: "Tentacruel",
      typeOne: "Water",
      typeTwo: "Poison",
      total: 515,
      hp: 80,
      attack: 70,
      defense: 65,
      specialAttack: 80,
      specialDefense: 120,
      speed: 100,
      generation: 1,
      isLegendary: false
    },
    {
      id: 74,
      name: "Geodude",
      typeOne: "Rock",
      typeTwo: "Ground",
      total: 300,
      hp: 40,
      attack: 80,
      defense: 100,
      specialAttack: 30,
      specialDefense: 30,
      speed: 20,
      generation: 1,
      isLegendary: false
    },
    {
      id: 75,
      name: "Graveler",
      typeOne: "Rock",
      typeTwo: "Ground",
      total: 390,
      hp: 55,
      attack: 95,
      defense: 115,
      specialAttack: 45,
      specialDefense: 45,
      speed: 35,
      generation: 1,
      isLegendary: false
    },
    {
      id: 76,
      name: "Golem",
      typeOne: "Rock",
      typeTwo: "Ground",
      total: 495,
      hp: 80,
      attack: 120,
      defense: 130,
      specialAttack: 55,
      specialDefense: 65,
      speed: 45,
      generation: 1,
      isLegendary: false
    },
    {
      id: 77,
      name: "Ponyta",
      typeOne: "Fire",
      typeTwo: "",
      total: 410,
      hp: 50,
      attack: 85,
      defense: 55,
      specialAttack: 65,
      specialDefense: 65,
      speed: 90,
      generation: 1,
      isLegendary: false
    },
    {
      id: 78,
      name: "Rapidash",
      typeOne: "Fire",
      typeTwo: "",
      total: 500,
      hp: 65,
      attack: 100,
      defense: 70,
      specialAttack: 80,
      specialDefense: 80,
      speed: 105,
      generation: 1,
      isLegendary: false
    },
    {
      id: 79,
      name: "Slowpoke",
      typeOne: "Water",
      typeTwo: "Psychic",
      total: 315,
      hp: 90,
      attack: 65,
      defense: 65,
      specialAttack: 40,
      specialDefense: 40,
      speed: 15,
      generation: 1,
      isLegendary: false
    },
    {
      id: 80,
      name: "Slowbro",
      typeOne: "Water",
      typeTwo: "Psychic",
      total: 490,
      hp: 95,
      attack: 75,
      defense: 110,
      specialAttack: 100,
      specialDefense: 80,
      speed: 30,
      generation: 1,
      isLegendary: false
    },
    {
      id: 81,
      name: "Magnemite",
      typeOne: "Electric",
      typeTwo: "Steel",
      total: 325,
      hp: 25,
      attack: 35,
      defense: 70,
      specialAttack: 95,
      specialDefense: 55,
      speed: 45,
      generation: 1,
      isLegendary: false
    },
    {
      id: 82,
      name: "Magneton",
      typeOne: "Electric",
      typeTwo: "Steel",
      total: 465,
      hp: 50,
      attack: 60,
      defense: 95,
      specialAttack: 120,
      specialDefense: 70,
      speed: 70,
      generation: 1,
      isLegendary: false
    },
    {
      id: 83,
      name: "Farfetch'd",
      typeOne: "Normal",
      typeTwo: "Flying",
      total: 352,
      hp: 52,
      attack: 65,
      defense: 55,
      specialAttack: 58,
      specialDefense: 62,
      speed: 60,
      generation: 1,
      isLegendary: false
    },
    {
      id: 84,
      name: "Doduo",
      typeOne: "Normal",
      typeTwo: "Flying",
      total: 310,
      hp: 35,
      attack: 85,
      defense: 45,
      specialAttack: 35,
      specialDefense: 35,
      speed: 75,
      generation: 1,
      isLegendary: false
    },
    {
      id: 85,
      name: "Dodrio",
      typeOne: "Normal",
      typeTwo: "Flying",
      total: 460,
      hp: 60,
      attack: 110,
      defense: 70,
      specialAttack: 60,
      specialDefense: 60,
      speed: 100,
      generation: 1,
      isLegendary: false
    },
    {
      id: 86,
      name: "Seel",
      typeOne: "Water",
      typeTwo: "",
      total: 325,
      hp: 65,
      attack: 45,
      defense: 55,
      specialAttack: 45,
      specialDefense: 70,
      speed: 45,
      generation: 1,
      isLegendary: false
    },
    {
      id: 87,
      name: "Dewgong",
      typeOne: "Water",
      typeTwo: "Ice",
      total: 475,
      hp: 90,
      attack: 70,
      defense: 80,
      specialAttack: 70,
      specialDefense: 95,
      speed: 70,
      generation: 1,
      isLegendary: false
    },
    {
      id: 88,
      name: "Grimer",
      typeOne: "Poison",
      typeTwo: "",
      total: 325,
      hp: 80,
      attack: 80,
      defense: 50,
      specialAttack: 40,
      specialDefense: 50,
      speed: 25,
      generation: 1,
      isLegendary: false
    },
    {
      id: 89,
      name: "Muk",
      typeOne: "Poison",
      typeTwo: "",
      total: 500,
      hp: 105,
      attack: 105,
      defense: 75,
      specialAttack: 65,
      specialDefense: 100,
      speed: 50,
      generation: 1,
      isLegendary: false
    },
    {
      id: 90,
      name: "Shellder",
      typeOne: "Water",
      typeTwo: "",
      total: 305,
      hp: 30,
      attack: 65,
      defense: 100,
      specialAttack: 45,
      specialDefense: 25,
      speed: 40,
      generation: 1,
      isLegendary: false
    },
    {
      id: 91,
      name: "Cloyster",
      typeOne: "Water",
      typeTwo: "Ice",
      total: 525,
      hp: 50,
      attack: 95,
      defense: 180,
      specialAttack: 85,
      specialDefense: 45,
      speed: 70,
      generation: 1,
      isLegendary: false
    },
    {
      id: 92,
      name: "Gastly",
      typeOne: "Ghost",
      typeTwo: "Poison",
      total: 310,
      hp: 30,
      attack: 35,
      defense: 30,
      specialAttack: 100,
      specialDefense: 35,
      speed: 80,
      generation: 1,
      isLegendary: false
    },
    {
      id: 93,
      name: "Haunter",
      typeOne: "Ghost",
      typeTwo: "Poison",
      total: 405,
      hp: 45,
      attack: 50,
      defense: 45,
      specialAttack: 115,
      specialDefense: 55,
      speed: 95,
      generation: 1,
      isLegendary: false
    },
    {
      id: 94,
      name: "Gengar",
      typeOne: "Ghost",
      typeTwo: "Poison",
      total: 500,
      hp: 60,
      attack: 65,
      defense: 60,
      specialAttack: 130,
      specialDefense: 75,
      speed: 110,
      generation: 1,
      isLegendary: false
    },
    {
      id: 95,
      name: "Onix",
      typeOne: "Rock",
      typeTwo: "Ground",
      total: 385,
      hp: 35,
      attack: 45,
      defense: 160,
      specialAttack: 30,
      specialDefense: 45,
      speed: 70,
      generation: 1,
      isLegendary: false
    },
    {
      id: 96,
      name: "Drowzee",
      typeOne: "Psychic",
      typeTwo: "",
      total: 328,
      hp: 60,
      attack: 48,
      defense: 45,
      specialAttack: 43,
      specialDefense: 90,
      speed: 42,
      generation: 1,
      isLegendary: false
    },
    {
      id: 97,
      name: "Hypno",
      typeOne: "Psychic",
      typeTwo: "",
      total: 483,
      hp: 85,
      attack: 73,
      defense: 70,
      specialAttack: 73,
      specialDefense: 115,
      speed: 67,
      generation: 1,
      isLegendary: false
    },
    {
      id: 98,
      name: "Krabby",
      typeOne: "Water",
      typeTwo: "",
      total: 325,
      hp: 30,
      attack: 105,
      defense: 90,
      specialAttack: 25,
      specialDefense: 25,
      speed: 50,
      generation: 1,
      isLegendary: false
    },
    {
      id: 99,
      name: "Kingler",
      typeOne: "Water",
      typeTwo: "",
      total: 475,
      hp: 55,
      attack: 130,
      defense: 115,
      specialAttack: 50,
      specialDefense: 50,
      speed: 75,
      generation: 1,
      isLegendary: false
    },
    {
      id: 100,
      name: "Voltorb",
      typeOne: "Electric",
      typeTwo: "",
      total: 330,
      hp: 40,
      attack: 30,
      defense: 50,
      specialAttack: 55,
      specialDefense: 55,
      speed: 100,
      generation: 1,
      isLegendary: false
    },
    {
      id: 101,
      name: "Electrode",
      typeOne: "Electric",
      typeTwo: "",
      total: 480,
      hp: 60,
      attack: 50,
      defense: 70,
      specialAttack: 80,
      specialDefense: 80,
      speed: 140,
      generation: 1,
      isLegendary: false
    },
    {
      id: 102,
      name: "Exeggcute",
      typeOne: "Grass",
      typeTwo: "Psychic",
      total: 325,
      hp: 60,
      attack: 40,
      defense: 80,
      specialAttack: 60,
      specialDefense: 45,
      speed: 40,
      generation: 1,
      isLegendary: false
    },
    {
      id: 103,
      name: "Exeggutor",
      typeOne: "Grass",
      typeTwo: "Psychic",
      total: 520,
      hp: 95,
      attack: 95,
      defense: 85,
      specialAttack: 125,
      specialDefense: 65,
      speed: 55,
      generation: 1,
      isLegendary: false
    },
    {
      id: 104,
      name: "Cubone",
      typeOne: "Ground",
      typeTwo: "",
      total: 320,
      hp: 50,
      attack: 50,
      defense: 95,
      specialAttack: 40,
      specialDefense: 50,
      speed: 35,
      generation: 1,
      isLegendary: false
    },
    {
      id: 105,
      name: "Marowak",
      typeOne: "Ground",
      typeTwo: "",
      total: 425,
      hp: 60,
      attack: 80,
      defense: 110,
      specialAttack: 50,
      specialDefense: 80,
      speed: 45,
      generation: 1,
      isLegendary: false
    },
    {
      id: 106,
      name: "Hitmonlee",
      typeOne: "Fighting",
      typeTwo: "",
      total: 455,
      hp: 50,
      attack: 120,
      defense: 53,
      specialAttack: 35,
      specialDefense: 110,
      speed: 87,
      generation: 1,
      isLegendary: false
    },
    {
      id: 107,
      name: "Hitmonchan",
      typeOne: "Fighting",
      typeTwo: "",
      total: 455,
      hp: 50,
      attack: 105,
      defense: 79,
      specialAttack: 35,
      specialDefense: 110,
      speed: 76,
      generation: 1,
      isLegendary: false
    },
    {
      id: 108,
      name: "Lickitung",
      typeOne: "Normal",
      typeTwo: "",
      total: 385,
      hp: 90,
      attack: 55,
      defense: 75,
      specialAttack: 60,
      specialDefense: 75,
      speed: 30,
      generation: 1,
      isLegendary: false
    },
    {
      id: 109,
      name: "Koffing",
      typeOne: "Poison",
      typeTwo: "",
      total: 340,
      hp: 40,
      attack: 65,
      defense: 95,
      specialAttack: 60,
      specialDefense: 45,
      speed: 35,
      generation: 1,
      isLegendary: false
    },
    {
      id: 110,
      name: "Weezing",
      typeOne: "Poison",
      typeTwo: "",
      total: 490,
      hp: 65,
      attack: 90,
      defense: 120,
      specialAttack: 85,
      specialDefense: 70,
      speed: 60,
      generation: 1,
      isLegendary: false
    },
    {
      id: 111,
      name: "Rhyhorn",
      typeOne: "Ground",
      typeTwo: "Rock",
      total: 345,
      hp: 80,
      attack: 85,
      defense: 95,
      specialAttack: 30,
      specialDefense: 30,
      speed: 25,
      generation: 1,
      isLegendary: false
    },
    {
      id: 112,
      name: "Rhydon",
      typeOne: "Ground",
      typeTwo: "Rock",
      total: 485,
      hp: 105,
      attack: 130,
      defense: 120,
      specialAttack: 45,
      specialDefense: 45,
      speed: 40,
      generation: 1,
      isLegendary: false
    },
    {
      id: 113,
      name: "Chansey",
      typeOne: "Normal",
      typeTwo: "",
      total: 450,
      hp: 250,
      attack: 5,
      defense: 5,
      specialAttack: 35,
      specialDefense: 105,
      speed: 50,
      generation: 1,
      isLegendary: false
    },
    {
      id: 114,
      name: "Tangela",
      typeOne: "Grass",
      typeTwo: "",
      total: 435,
      hp: 65,
      attack: 55,
      defense: 115,
      specialAttack: 100,
      specialDefense: 40,
      speed: 60,
      generation: 1,
      isLegendary: false
    },
    {
      id: 115,
      name: "Kangaskhan",
      typeOne: "Normal",
      typeTwo: "",
      total: 490,
      hp: 105,
      attack: 95,
      defense: 80,
      specialAttack: 40,
      specialDefense: 80,
      speed: 90,
      generation: 1,
      isLegendary: false
    },
    {
      id: 116,
      name: "Horsea",
      typeOne: "Water",
      typeTwo: "",
      total: 295,
      hp: 30,
      attack: 40,
      defense: 70,
      specialAttack: 70,
      specialDefense: 25,
      speed: 60,
      generation: 1,
      isLegendary: false
    },
    {
      id: 117,
      name: "Seadra",
      typeOne: "Water",
      typeTwo: "",
      total: 440,
      hp: 55,
      attack: 65,
      defense: 95,
      specialAttack: 95,
      specialDefense: 45,
      speed: 85,
      generation: 1,
      isLegendary: false
    },
    {
      id: 118,
      name: "Goldeen",
      typeOne: "Water",
      typeTwo: "",
      total: 320,
      hp: 45,
      attack: 67,
      defense: 60,
      specialAttack: 35,
      specialDefense: 50,
      speed: 63,
      generation: 1,
      isLegendary: false
    },
    {
      id: 119,
      name: "Seaking",
      typeOne: "Water",
      typeTwo: "",
      total: 450,
      hp: 80,
      attack: 92,
      defense: 65,
      specialAttack: 65,
      specialDefense: 80,
      speed: 68,
      generation: 1,
      isLegendary: false
    },
    {
      id: 120,
      name: "Staryu",
      typeOne: "Water",
      typeTwo: "",
      total: 340,
      hp: 30,
      attack: 45,
      defense: 55,
      specialAttack: 70,
      specialDefense: 55,
      speed: 85,
      generation: 1,
      isLegendary: false
    },
    {
      id: 121,
      name: "Starmie",
      typeOne: "Water",
      typeTwo: "Psychic",
      total: 520,
      hp: 60,
      attack: 75,
      defense: 85,
      specialAttack: 100,
      specialDefense: 85,
      speed: 115,
      generation: 1,
      isLegendary: false
    },
    {
      id: 122,
      name: "Mr. Mime",
      typeOne: "Psychic",
      typeTwo: "Fairy",
      total: 460,
      hp: 40,
      attack: 45,
      defense: 65,
      specialAttack: 100,
      specialDefense: 120,
      speed: 90,
      generation: 1,
      isLegendary: false
    },
    {
      id: 123,
      name: "Scyther",
      typeOne: "Bug",
      typeTwo: "Flying",
      total: 500,
      hp: 70,
      attack: 110,
      defense: 80,
      specialAttack: 55,
      specialDefense: 80,
      speed: 105,
      generation: 1,
      isLegendary: false
    },
    {
      id: 124,
      name: "Jynx",
      typeOne: "Ice",
      typeTwo: "Psychic",
      total: 455,
      hp: 65,
      attack: 50,
      defense: 35,
      specialAttack: 115,
      specialDefense: 95,
      speed: 95,
      generation: 1,
      isLegendary: false
    },
    {
      id: 125,
      name: "Electabuzz",
      typeOne: "Electric",
      typeTwo: "",
      total: 490,
      hp: 65,
      attack: 83,
      defense: 57,
      specialAttack: 95,
      specialDefense: 85,
      speed: 105,
      generation: 1,
      isLegendary: false
    },
    {
      id: 126,
      name: "Magmar",
      typeOne: "Fire",
      typeTwo: "",
      total: 495,
      hp: 65,
      attack: 95,
      defense: 57,
      specialAttack: 100,
      specialDefense: 85,
      speed: 93,
      generation: 1,
      isLegendary: false
    },
    {
      id: 127,
      name: "Pinsir",
      typeOne: "Bug",
      typeTwo: "",
      total: 500,
      hp: 65,
      attack: 125,
      defense: 100,
      specialAttack: 55,
      specialDefense: 70,
      speed: 85,
      generation: 1,
      isLegendary: false
    },
    {
      id: 128,
      name: "Tauros",
      typeOne: "Normal",
      typeTwo: "",
      total: 490,
      hp: 75,
      attack: 100,
      defense: 95,
      specialAttack: 40,
      specialDefense: 70,
      speed: 110,
      generation: 1,
      isLegendary: false
    },
    {
      id: 129,
      name: "Magikarp",
      typeOne: "Water",
      typeTwo: "",
      total: 200,
      hp: 20,
      attack: 10,
      defense: 55,
      specialAttack: 15,
      specialDefense: 20,
      speed: 80,
      generation: 1,
      isLegendary: false
    },
    {
      id: 130,
      name: "Gyarados",
      typeOne: "Water",
      typeTwo: "Flying",
      total: 540,
      hp: 95,
      attack: 125,
      defense: 79,
      specialAttack: 60,
      specialDefense: 100,
      speed: 81,
      generation: 1,
      isLegendary: false
    },
    {
      id: 131,
      name: "Lapras",
      typeOne: "Water",
      typeTwo: "Ice",
      total: 535,
      hp: 130,
      attack: 85,
      defense: 80,
      specialAttack: 85,
      specialDefense: 95,
      speed: 60,
      generation: 1,
      isLegendary: false
    },
    {
      id: 132,
      name: "Ditto",
      typeOne: "Normal",
      typeTwo: "",
      total: 288,
      hp: 48,
      attack: 48,
      defense: 48,
      specialAttack: 48,
      specialDefense: 48,
      speed: 48,
      generation: 1,
      isLegendary: false
    },
    {
      id: 133,
      name: "Eevee",
      typeOne: "Normal",
      typeTwo: "",
      total: 325,
      hp: 55,
      attack: 55,
      defense: 50,
      specialAttack: 45,
      specialDefense: 65,
      speed: 55,
      generation: 1,
      isLegendary: false
    },
    {
      id: 134,
      name: "Vaporeon",
      typeOne: "Water",
      typeTwo: "",
      total: 525,
      hp: 130,
      attack: 65,
      defense: 60,
      specialAttack: 110,
      specialDefense: 95,
      speed: 65,
      generation: 1,
      isLegendary: false
    },
    {
      id: 135,
      name: "Jolteon",
      typeOne: "Electric",
      typeTwo: "",
      total: 525,
      hp: 65,
      attack: 65,
      defense: 60,
      specialAttack: 110,
      specialDefense: 95,
      speed: 130,
      generation: 1,
      isLegendary: false
    },
    {
      id: 136,
      name: "Flareon",
      typeOne: "Fire",
      typeTwo: "",
      total: 525,
      hp: 65,
      attack: 130,
      defense: 60,
      specialAttack: 95,
      specialDefense: 110,
      speed: 65,
      generation: 1,
      isLegendary: false
    },
    {
      id: 137,
      name: "Porygon",
      typeOne: "Normal",
      typeTwo: "",
      total: 395,
      hp: 65,
      attack: 60,
      defense: 70,
      specialAttack: 85,
      specialDefense: 75,
      speed: 40,
      generation: 1,
      isLegendary: false
    },
    {
      id: 138,
      name: "Omanyte",
      typeOne: "Rock",
      typeTwo: "Water",
      total: 355,
      hp: 35,
      attack: 40,
      defense: 100,
      specialAttack: 90,
      specialDefense: 55,
      speed: 35,
      generation: 1,
      isLegendary: false
    },
    {
      id: 139,
      name: "Omastar",
      typeOne: "Rock",
      typeTwo: "Water",
      total: 495,
      hp: 70,
      attack: 60,
      defense: 125,
      specialAttack: 115,
      specialDefense: 70,
      speed: 55,
      generation: 1,
      isLegendary: false
    },
    {
      id: 140,
      name: "Kabuto",
      typeOne: "Rock",
      typeTwo: "Water",
      total: 355,
      hp: 30,
      attack: 80,
      defense: 90,
      specialAttack: 55,
      specialDefense: 45,
      speed: 55,
      generation: 1,
      isLegendary: false
    },
    {
      id: 141,
      name: "Kabutops",
      typeOne: "Rock",
      typeTwo: "Water",
      total: 495,
      hp: 60,
      attack: 115,
      defense: 105,
      specialAttack: 65,
      specialDefense: 70,
      speed: 80,
      generation: 1,
      isLegendary: false
    },
    {
      id: 142,
      name: "Aerodactyl",
      typeOne: "Rock",
      typeTwo: "Flying",
      total: 515,
      hp: 80,
      attack: 105,
      defense: 65,
      specialAttack: 60,
      specialDefense: 75,
      speed: 130,
      generation: 1,
      isLegendary: false
    },
    {
      id: 143,
      name: "Snorlax",
      typeOne: "Normal",
      typeTwo: "",
      total: 540,
      hp: 160,
      attack: 110,
      defense: 65,
      specialAttack: 65,
      specialDefense: 110,
      speed: 30,
      generation: 1,
      isLegendary: false
    },
    {
      id: 144,
      name: "Articuno",
      typeOne: "Ice",
      typeTwo: "Flying",
      total: 580,
      hp: 90,
      attack: 85,
      defense: 100,
      specialAttack: 95,
      specialDefense: 125,
      speed: 85,
      generation: 1,
      isLegendary: true
    },
    {
      id: 145,
      name: "Zapdos",
      typeOne: "Electric",
      typeTwo: "Flying",
      total: 580,
      hp: 90,
      attack: 90,
      defense: 85,
      specialAttack: 125,
      specialDefense: 90,
      speed: 100,
      generation: 1,
      isLegendary: true
    },
    {
      id: 146,
      name: "Moltres",
      typeOne: "Fire",
      typeTwo: "Flying",
      total: 580,
      hp: 90,
      attack: 100,
      defense: 90,
      specialAttack: 125,
      specialDefense: 85,
      speed: 90,
      generation: 1,
      isLegendary: true
    },
    {
      id: 147,
      name: "Dratini",
      typeOne: "Dragon",
      typeTwo: "",
      total: 300,
      hp: 41,
      attack: 64,
      defense: 45,
      specialAttack: 50,
      specialDefense: 50,
      speed: 50,
      generation: 1,
      isLegendary: false
    },
    {
      id: 148,
      name: "Dragonair",
      typeOne: "Dragon",
      typeTwo: "",
      total: 420,
      hp: 61,
      attack: 84,
      defense: 65,
      specialAttack: 70,
      specialDefense: 70,
      speed: 70,
      generation: 1,
      isLegendary: false
    },
    {
      id: 149,
      name: "Dragonite",
      typeOne: "Dragon",
      typeTwo: "Flying",
      total: 600,
      hp: 91,
      attack: 134,
      defense: 95,
      specialAttack: 100,
      specialDefense: 100,
      speed: 80,
      generation: 1,
      isLegendary: false
    },
    {
      id: 150,
      name: "Mewtwo",
      typeOne: "Psychic",
      typeTwo: "",
      total: 680,
      hp: 106,
      attack: 110,
      defense: 90,
      specialAttack: 154,
      specialDefense: 90,
      speed: 130,
      generation: 1,
      isLegendary: true
    },
    {
      id: 151,
      name: "Mew",
      typeOne: "Psychic",
      typeTwo: "",
      total: 600,
      hp: 100,
      attack: 100,
      defense: 100,
      specialAttack: 100,
      specialDefense: 100,
      speed: 100,
      generation: 1,
      isLegendary: false
    }
  ]
};
